### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by ShahierNashaat** [Taher-web-dev/Space-Travelers-Hub#25]
https://github.com/Taher-web-dev/Space-Travelers-Hub/projects/1

2 teammates on the team.

**Comment by Mihndim2020** [comment]
# STATUS: INVALID!!!  :x: :x: :x: 

Hi Team,

Your pull request is invalid, please make sure your implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._
- [ ] Kindly submit a link to your GitHub project(`kanban board`) in this issue.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by o-rashad** [comment]
Asslam Alaikum team @ShahierNashaat @Taher-web-dev  ,😊

Hi👋🏽, Your mikestone is complete!  

good luck with upcoming milestones :muscle: 

# Congratulations! 🎉 

Happy coding!👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
